# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: echo.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'echo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\x0f\x61genttrace.test\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xec\x01\n\x04\x45\x63ho\x12H\n\tUnaryEcho\x12\x1c.agenttrace.test.EchoRequest\x1a\x1d.agenttrace.test.EchoResponse\x12N\n\rStreamingEcho\x12\x1c.agenttrace.test.EchoRequest\x1a\x1d.agenttrace.test.EchoResponse0\x01\x12J\n\x0b\x46\x61ilingEcho\x12\x1c.agenttrace.test.EchoRequest\x1a\x1d.agenttrace.test.EchoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECHOREQUEST']._serialized_start=31
  _globals['_ECHOREQUEST']._serialized_end=61
  _globals['_ECHORESPONSE']._serialized_start=63
  _globals['_ECHORESPONSE']._serialized_end=94
  _globals['_ECHO']._serialized_start=97
  _globals['_ECHO']._serialized_end=333
# @@protoc_insertion_point(module_scope)
